'use strict';
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?s.split('-').reverse().join('/'):'Não informada';
const uid=()=>crypto.randomUUID();
const rows=(a)=>a.map(([description,value,date])=>({id:uid(),description,value,date}));
const seed={vehicles:[{id:'r19',name:'Jeep Renegade 2019',partners:'Marcelo / Nel',date:'2026-07-24',purchase:5800000,target:7000000,costs:rows([['4 pneus novos',179132,'2026-07-24'],['Suspensão Beneta',6600,'2026-07-24'],['Galego Suspensão',39400,'2026-07-24'],['Alinhamento e balanceamento',18000,'2026-07-24'],['Retrovisor (lente do pisca)',8000,'2026-07-27'],['Jorge som Mamão',38800,'2026-07-27'],['Limpa do para-brisa',5000,'2026-07-27'],['Emissão documento do Onix de Nel (DUT)',8000,'2026-07-27'],['Pintura Adson',80000,'2026-07-27'],['Rene',80000,'2026-08-05'],['Lavagem',23000,'2026-08-11'],['Polimento',25000,'2026-08-11'],['Gasolina',5000,'2026-08-11'],['Fita dupla face',4000,'2026-08-11'],['Jorge som Marcelo',5000,'2026-08-12']])},{id:'r18',name:'Jeep Renegade 2018',partners:'Marcelo / Marcelo / Gil',date:'2026-07-28',purchase:5600000,target:6800000,costs:rows([['Propaganda',50000,'2026-07-31'],['Remoção reboque',10000,'2026-07-31'],['Rene',90000,'2026-08-05'],['Polimento',22000,'2026-08-05'],['Gasolina',5000,'2026-08-05'],['Despachante (transferência para o nome da loja)',118000,'2026-09-03'],['Vistoria + cartório (Mamão)',38200,'2026-09-03'],['Higienização',15000,'2026-09-08']])}],opening:-292696,transactions:[]};
const fox2018={id:'fox-connect-2018-branco-marcelo',name:'Fox Connect 2018 1.6 branco',partners:'Marcelo',date:'',purchase:4870000,target:6870000,costs:rows([['Baixa gravame',9000,''],['Gasolina',5000,''],['Propaganda setembro',50000,''],['Martelinho',30000,'2026-09-03'],['Higienização',15000,'2026-09-08']])};
seed.vehicles.push(fox2018);
const KEY='mamaocar-financeiro-v1';let state;let storageProblem=false;try{const raw=localStorage.getItem(KEY);state=raw?JSON.parse(raw):seed;if(!Array.isArray(state.vehicles)||!Array.isArray(state.transactions)||!Number.isSafeInteger(state.opening))throw Error();}catch{state=seed;storageProblem=true;}
// Add the new worksheet once, preserving all previously saved records.
if(!state.vehicles.some(v=>v.id===fox2018.id)){
 state.vehicles.push(fox2018);
 if(!storageProblem){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageProblem=true;}}
}
let view='veiculos',selected=state.vehicles[0]?.id;const $=s=>document.querySelector(s);const total=v=>v.costs.reduce((s,c)=>s+c.value,0);const sum=(xs,f)=>xs.reduce((s,x)=>s+f(x),0);let submitAction;
function notify(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{notify('Não foi possível salvar. O armazenamento do navegador está indisponível.');return false}}
function stat(label,value,note,cls=''){return `<div class="stat ${cls}"><label>${label}</label><strong>${value}</strong><small>${note}</small></div>`}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#crumb').textContent=view==='veiculos'?'Veículos':'Caixa parado';$('#title').textContent=view==='veiculos'?'Custos dos veículos':'Caixa parado';$('#subtitle').textContent=view==='veiculos'?'Cada investimento, do primeiro serviço à venda.':'Entradas, saídas e saldo disponível da loja.';$('#primary').textContent=view==='veiculos'?'+ Novo veículo':'+ Novo lançamento';if(view==='veiculos')renderVehicles();else renderCash()}
function renderVehicles(){const costs=sum(state.vehicles,total),purchase=sum(state.vehicles,v=>v.purchase),profit=sum(state.vehicles,v=>v.target-v.purchase-total(v));$('#stats').innerHTML=stat('Veículos cadastrados',String(state.vehicles.length).padStart(2,'0'),'Controle individual por veículo')+stat('Custos registrados',money(costs),'Serviços e despesas')+stat('Total investido',money(purchase+costs),'Compra + custos registrados')+stat('Lucro estimado',money(profit),'Considerando as vendas previstas','accent');const v=state.vehicles.find(v=>v.id===selected)||state.vehicles[0];if(v)selected=v.id;$('#workspace').innerHTML=`<div class="columns"><section class="panel"><div class="panelhead"><h2>Seus veículos</h2><span class="count">${state.vehicles.length}</span></div><div class="vehicles">${state.vehicles.map(x=>`<button class="vehicle ${v?.id===x.id?'selected':''}" data-select="${esc(x.id)}"><strong>${esc(x.name)}</strong><span>${esc(x.partners)||'Sócios não informados'}</span><small>Investido <b>${money(x.purchase+total(x))}</b></small></button>`).join('')}</div></section>${v?detail(v):'<div class="panel empty">Cadastre um veículo para começar.</div>'}</div>`;document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{selected=b.dataset.select;render()});if(v){$('#addCost').onclick=()=>costModal(v);$('#editVehicle').onclick=()=>vehicleModal(v);document.querySelectorAll('[data-edit-cost]').forEach(b=>b.onclick=()=>costModal(v,v.costs.find(c=>c.id===b.dataset.editCost)));document.querySelectorAll('[data-delete-cost]').forEach(b=>b.onclick=()=>remove('Excluir este custo?',()=>v.costs=v.costs.filter(c=>c.id!==b.dataset.deleteCost)));}}
function detail(v){const c=total(v);return `<section class="panel"><div class="detailtitle"><div><h2>${esc(v.name)}</h2><div class="sub">${esc(v.partners)} · ${v.date?`Entrada em ${date(v.date)}`:'Data de entrada não informada'}</div></div><button id="editVehicle" class="iconbtn" aria-label="Editar dados do veículo">Editar</button></div><div class="summary"><div><span>Valor de compra</span><strong>${money(v.purchase)}</strong></div><div><span>Venda prevista</span><strong>${money(v.target)}</strong></div><div><span>Lucro estimado</span><strong class="${v.target-v.purchase-c>=0?'green':'red'}">${money(v.target-v.purchase-c)}</strong></div></div><div class="tabletitle"><h3>Serviços e custos <span class="count">${v.costs.length}</span></h3><button id="addCost">+ Adicionar custo</button></div><div class="tablewrap"><table><thead><tr><th>SERVIÇO / DESCRIÇÃO</th><th>DATA</th><th class="money">VALOR</th><th></th></tr></thead><tbody>${v.costs.map(c=>`<tr><td>${esc(c.description)}</td><td class="date">${date(c.date)}</td><td class="money">${money(c.value)}</td><td><button class="iconbtn" data-edit-cost="${esc(c.id)}" aria-label="Editar ${esc(c.description)}">✎</button><button class="iconbtn" data-delete-cost="${esc(c.id)}" aria-label="Excluir ${esc(c.description)}">×</button></td></tr>`).join('')}<tr class="tabletotal"><td colspan="2">Total de custos</td><td class="money">${money(c)}</td><td></td></tr></tbody></table></div></section>`}
function renderCash(){const incoming=sum(state.transactions.filter(t=>t.type==='in'),t=>t.value),outgoing=sum(state.transactions.filter(t=>t.type==='out'),t=>t.value);$('#stats').innerHTML=stat('Saldo inicial',money(state.opening),'Saldo informado no print')+stat('Novas entradas',money(incoming),'Após o saldo inicial')+stat('Novas saídas',money(outgoing),'Após o saldo inicial')+stat('Saldo disponível',money(state.opening+incoming-outgoing),'Saldo inicial + entradas − saídas','accent');$('#workspace').innerHTML=`<p class="cashnote">O histórico do print está incompleto. O saldo informado foi adotado como ponto de partida, sem repetir as movimentações anteriores. Custos dos veículos não são debitados automaticamente deste caixa.</p><section class="panel"><div class="panelhead"><h2>Movimentações do caixa</h2><button id="opening">Editar saldo inicial</button></div><div class="tablewrap"><table><thead><tr><th>DESCRIÇÃO</th><th>DATA</th><th>TIPO</th><th class="money">VALOR</th><th></th></tr></thead><tbody>${[...state.transactions].reverse().map(t=>`<tr><td>${esc(t.description)}</td><td class="date">${date(t.date)}</td><td class="${t.type==='in'?'green':'red'}">${t.type==='in'?'Entrada':'Saída'}</td><td class="money ${t.type==='in'?'green':'red'}">${t.type==='in'?'+':'−'} ${money(t.value)}</td><td><button class="iconbtn" data-edit-transaction="${esc(t.id)}" aria-label="Editar lançamento">✎</button><button class="iconbtn" data-delete-transaction="${esc(t.id)}" aria-label="Excluir lançamento">×</button></td></tr>`).join('')}</tbody></table>${state.transactions.length?'':'<div class="empty">Nenhuma nova movimentação.<br>Adicione uma entrada ou saída para atualizar o saldo.</div>'}</div></section>`;$('#opening').onclick=()=>openModal('Saldo inicial',field('value','Saldo inicial (R$)',(state.opening/100).toFixed(2),'number','step="0.01"'),f=>{state.opening=amount(f.get('value'),true)});document.querySelectorAll('[data-edit-transaction]').forEach(b=>b.onclick=()=>cashModal(state.transactions.find(t=>t.id===b.dataset.editTransaction)));document.querySelectorAll('[data-delete-transaction]').forEach(b=>b.onclick=()=>remove('Excluir esta movimentação?',()=>state.transactions=state.transactions.filter(t=>t.id!==b.dataset.deleteTransaction)));}
function field(name,label,value='',type='text',attrs=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='date'?'':'required'} ${attrs}></label>`}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function amount(s,signed=false){const n=Number(s);const cents=Math.round(n*100);if(!Number.isFinite(n)||!Number.isSafeInteger(cents)||(!signed&&cents<0)||Math.abs(cents)>1e13)throw Error('Informe um valor válido.');return cents}
function textValue(s){if(!s||!s.trim())throw Error('Preencha a descrição.');return s.trim()}
function openModal(title,fields,action){$('#modalTitle').textContent=title;$('#fields').innerHTML=fields;$('#formError').textContent='';submitAction=action;$('#dialog').showModal()}
function vehicleModal(v){openModal(v?'Editar veículo':'Novo veículo',field('name','Modelo e ano',v?.name??'')+field('partners','Sócios / responsáveis',v?.partners??'')+field('date','Data de entrada',v?.date??today(),'date')+field('purchase','Valor de compra (R$)',((v?.purchase??0)/100).toFixed(2),'number','min="0" step="0.01"')+field('target','Venda prevista (R$)',((v?.target??0)/100).toFixed(2),'number','min="0" step="0.01"'),f=>{const data={name:textValue(f.get('name')),partners:textValue(f.get('partners')),date:f.get('date'),purchase:amount(f.get('purchase')),target:amount(f.get('target'))};if(v)Object.assign(v,data);else{const x={id:uid(),...data,costs:[]};state.vehicles.push(x);selected=x.id}})}
function costModal(v,c){openModal(c?'Editar custo':'Adicionar custo',field('description','Serviço / descrição',c?.description??'')+field('date','Data',c?.date??today(),'date')+field('value','Valor (R$)',c?(c.value/100).toFixed(2):'','number','min="0.01" step="0.01"'),f=>{const data={description:textValue(f.get('description')),date:f.get('date'),value:amount(f.get('value'))};if(c)Object.assign(c,data);else v.costs.push({id:uid(),...data})})}
function cashModal(t){openModal(t?'Editar movimentação':'Novo lançamento',`<label>Tipo<select name="type"><option value="in" ${t?.type==='in'?'selected':''}>Entrada</option><option value="out" ${t?.type==='out'?'selected':''}>Saída</option></select></label>`+field('description','Descrição',t?.description??'')+field('date','Data',t?.date??today(),'date')+field('value','Valor (R$)',t?(t.value/100).toFixed(2):'','number','min="0.01" step="0.01"'),f=>{const data={type:f.get('type'),description:textValue(f.get('description')),date:f.get('date'),value:amount(f.get('value'))};if(t)Object.assign(t,data);else state.transactions.push({id:uid(),...data})})}
function remove(title,action){openModal(title,'<p>O total será recalculado após a exclusão.</p>',action)}
$('#form').onsubmit=e=>{e.preventDefault();try{submitAction(new FormData(e.target));const saved=persist();$('#dialog').close();render();if(saved)notify('Alteração salva.')}catch(e){$('#formError').textContent=e.message}};$('#close').onclick=$('#cancel').onclick=()=>$('#dialog').close();$('#primary').onclick=()=>view==='veiculos'?vehicleModal():cashModal();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});render();if(storageProblem)notify('Não foi possível acessar ou atualizar o armazenamento local. Confira seus dados antes de continuar.');
